application: sharelinktest
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: web/static
  
- url: /index
  script: web.pages.index.app
  
- url: /details
  script: web.pages.details.app
  
- url: /contactuspage
  script: web.pages.contactuspage.app
  
- url: /sendcontactus
  script: web.pages.contactuspage.app
  
- url: /contactspage
  script: web.pages.contactspage.app
  
- url: /addContact
  script: web.pages.contactspage.app
  
- url: /addGroup
  script: web.pages.mygroups.app

- url: /deletecontact
  script: web.pages.contactspage.app
  
- url: /mygroups
  script: web.pages.mygroups.app
  
- url: /mysavedlinks
  script: web.pages.mysavedlinks.app
  
- url: /addLink
  script: web.pages.mysavedlinks.app

- url: /share
  script: web.pages.mysavedlinks.app

- url: /deletelink
  script: web.pages.mysavedlinks.app
  
- url: /newlinks
  script: web.pages.newlinks.app
  
- url: /sign_up
  script: web.pages.sign_up.app
  
- url: /sign_up_buttom
  script: web.pages.sign_up_buttom.app
  
- url: /login
  script: web.pages.sign_up_buttom.app
  
- url: /logout
  script: web.pages.sign_up_buttom.app

- url: /sendmail
  script: web.pages.index.app
  
- url: /
  script: web.pages.index.app
  
- url: .*
  script: main.app
  
libraries:
- name: webapp2
  version: "2.5.2"